### ISSUE TITLE
needs updated

### ISSUE THREAD

**Issue by ziicutie** [Joedobo27/RockSurfaceTerraformingMod#1]
needs updated to 1.4.1

**Comment by Joedobo27** [comment]
There won't be anymore releases for this. On WU forums you'll see this mod is now "ABANDONED". I'm sorry but keeping the bytecode style modification updated is too much work. I may push updates as I do use it privately, but like I said, no more public releases. 
You're free to do whatever you want with the source if you want to try and fix any issues yourself.

**Comment by ziicutie** [comment]
Oh my apologies, I sometimes read but don't really pay attention to what I am reading exactly. Everybody gets them people online to deal with. :P
